name: homework 1

on:
  push:
    branches: [ homework1 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
           python-version: '3.8'
           architecture: x64
      - run: |
          python setup.py install
      - run: |
          flake8
      - run: |
          pytest